[package]
name = "raft_reconfigurator"
version = "0.1.0"
authors = ["Rohit <rohitju07@gmail.com>"]

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"

[dependencies]
getopts = "0.2.11"
mio = "0.3.5"
